title: Jami Virtanen
email: jamimvirtanen@gmail.com
description: Open to Work
show_downloads: false
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitLab
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/jmvirtan
- name: GitLab
    icon: <i class="fa-brands fa-gitlab"></i>
    link: https://gitlab.com/jmvirtan

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
